### ISSUE TITLE
Unterminated JSX contents 

### ISSUE THREAD

**Issue by r0m4** [roman01la/html-to-react-components#50]
I have tried to convert html to React, but received such an error

Romans-MacBook-Pro:test r0m4$ sudo html2react index.html
/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:9750
      throw error;
      ^

SyntaxError: Unterminated JSX contents (1158:11)
  1156 |     </div>
  1157 |   </footer>
> 1158 |     </div>;
       |           ^
  1159 |   }
  1160 | 
  1161 | }
    at e (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/parser-babylon.js:1:282)
    at Object.parse (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/parser-babylon.js:1:262260)
    at Object.parse (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:9739:19)
    at coreFormat (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:13252:23)
    at format (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:13526:12)
    at /usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:44207:15
    at Object.format (/usr/local/lib/node_modules/html-to-react-components/node_modules/prettier/index.js:44226:12)
    at /usr/local/lib/node_modules/html-to-react-components/lib/format.js:5:27
    at Array.reduce (<anonymous>) {
  loc: { start: { line: 1158, column: 11 } },
  codeFrame: '\x1B[0m \x1B[90m 1156 | \x1B[39m    \x1B[33m<\x1B[39m\x1B[33m/\x1B[39m\x1B[33mdiv\x1B[39m\x1B[33m>\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 1157 | \x1B[39m  \x1B[33m<\x1B[39m\x1B[33m/\x1B[39m\x1B[33mfooter\x1B[39m\x1B[33m>\x1B[39m\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 1158 | \x1B[39m    \x1B[33m<\x1B[39m\x1B[33m/\x1B[39m\x1B[33mdiv\x1B[39m\x1B[33m>\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m      | \x1B[39m          \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 1159 | \x1B[39m  }\x1B[0m\n' +
    '\x1B[0m \x1B[90m 1160 | \x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 1161 | \x1B[39m}\x1B[0m'
} 

here is the HTML that I tried to convert: https://drive.google.com/file/d/1JYDMWeFsBl1bJU0Oz8UtlOBBYOjuSepI/view?usp=sharing

**Comment by roman01la** [comment]
I'd suggest to pass only actual HTML in the `<body>` tag and if the issue still exists try to remove HTML content tag by tag to identify where the problem is.

**Comment by r0m4** [comment]
проще руками перенести в реакт, чем сидеть вот это искать на какой же строке ошибка, и когда найдешь, всеравно руками придется переносить.
