### ISSUE TITLE
SyntaxError: Unexpected token, expected , (3:88)

### ISSUE THREAD

**Issue by raniaamina** [roman01la/html-to-react-components#68]
Hi I try to use this tool at first time and get this error. What should i do for fixing it?

```bash
html2react ./zectStudioPages/index.html -o ./src/components                                                                                                                                                                                                   
/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:4633
    throw err;
    ^

SyntaxError: Unexpected token, expected , (3:88)
    at Parser.pp$5.raise (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:4630:15)
    at Parser.pp.unexpected (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:1911:10)
    at Parser.pp.expect (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:1899:35)
    at Parser.pp$3.parseObj (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:4148:18)
    at Parser.pp$3.parseExprAtom (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:3885:29)
    at Parser.parseExprAtom (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:7426:30)
    at Parser.pp$3.parseExprSubscripts (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:3655:21)
    at Parser.pp$3.parseMaybeUnary (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:3635:21)
    at Parser.pp$3.parseExprOps (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:3565:21)
    at Parser.pp$3.parseMaybeConditional (/home/sherlock/.nvm/versions/node/v13.2.0/lib/node_modules/html-to-react-components/node_modules/babylon/lib/index.js:3542:21) {
  pos: 263,
  loc: Position { line: 3, column: 88 }
}
```

**Comment by roman01la** [comment]
At first a quick repro would be helpful
